# This is a basic workflow to help you get started with Actions

name: Horadrim Cube Project CD for main branch

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Extract tag version
        id: tag_version
        run: |
          . setup.sh
          echo "::set-output name=cube_version::$HM_CUBE_VERSION"

      # Runs a set of commands using the runners shell
      - name: Package deb package
        run: |
          . setup.sh
          make
          make deb

      - name: Create Tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          tag: ${{ steps.tag_version.outputs.cube_version }}
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy debian
        uses: actions/upload-artifact@v2
        with:
          name: hm-cube-${{ steps.tag_version.outputs.cube_version }}-deb
          path: Horadric-Cube-${{ steps.tag_version.outputs.cube_version }}_amd64.deb
